export type JobStatus = {
  url: string;
  publisher_id: string;
  status: string;
  attempt_count: number;
  current_job_id?: string | null;
  worker_id?: string | null;
  last_error?: string | null;
  error_type?: string | null;
  heartbeat_at?: string | null;
  heartbeat_interval_seconds: number;
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  healed: boolean;
  reprocessed_count: number;
  last_reprocessed_at?: string | null;
  tags: string[];
};
